algoritmo "mediador"
var
    distancia: real
inicio
    escreva("Digite uma distancia em metros: ")
    leia(distancia)
    escreval(distancia, "m corresponde a:")
    escreval(distancia / 1000, " km")
    escreval(distancia / 100, " hm")
    escreval(distancia / 10, " dam")
    escreval(distancia * 10, " dm")
    escreval(distancia * 100, " cm")
    escreval(distancia * 1000, " mm")

fimalgoritmo